deployment:
  name: "default"

ingress:
  hostName: ""
  hostNames: "" # <-- This is a list of hostnames for the ingress
  ingressClassName: ""
  annotations: {}
  s3Behavior:
    enabled: true
    spa:
      enabled: false
  rules:

certManager:
  enabled: false
  namespace: cert-manager
  email: admin@example.com
  privateKeySecretRef: default
  http01:
    enabled: true
  dns01:
    cloudflare:
      enabled: false
      apiTokenSecretName: ""
      apiTokenSecretKey: ""
